name: Build and sign release APK
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Decode keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.KEYSTORE_BASE64_ENCODED }}
        run: |
          echo $ENCODED_KEYSTORE | base64 --decode > "$GITHUB_WORKSPACE/app/keystore.jks"

      - name: Build release APK
        env:
          API_KEY: ${{ secrets.API_KEY }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: ./gradlew bundleRelease


      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: Build artifacts
          path: app/build/outputs/
